apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy-managed-services-config
data:
  static-sa.json: |-
    [
      {
        "name": "static-sa",
        "client_id": "svc-static",
        "client_secret": "the-static-secret"
      }
    ]