apiVersion: v1
kind: Service
metadata:
  labels:
    app: dummy-managed-services
  name: dummy-managed-services
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: dummy-managed-services
  type: ClusterIP
