# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install JDK 11
      # Uses sha for added security since tags can be updated
      uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
      with:
        java-version: 11
    - name: Build Quarkus main
      run: |
        git clone https://github.com/quarkusio/quarkus.git
        cd quarkus
        ./mvnw -T1C -e -B --settings .github/mvn-settings.xml clean install -Dquickly-ci
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: export LANG=en_US && ./mvnw -e -B -fae clean install -Dstart-containers
    - name: Delete Local Artifacts From Cache
      shell: bash
      run: rm -rf ~/.m2/repository/com/openshift/cloud/dummy-managed-services
